//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webEstacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class patentes
    {
        public int Id { get; set; }
        public string Patente { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_Egreso { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Monto { get; set; }
    }
}
